// import 'dart:io';
// import 'package:flutter/material.dart';
// import 'package:pdf/pdf.dart';
// import 'package:pdf/widgets.dart' as pw;
// import 'package:printing/printing.dart';
// import 'package:path_provider/path_provider.dart';
//
// import '../../../../model/property_model.dart';
//
// void generateAndDownloadPdf(BuildContext context, Occupant occupant, Property property) async {
//   final pdf = pw.Document();
//
//   // Define a reusable theme
//   final baseTextStyle = pw.TextStyle(
//     fontSize: 12,
//     color: PdfColors.blueGrey800,
//   );
//
//   final headerTextStyle = pw.TextStyle(
//     fontSize: 18,
//     fontWeight: pw.FontWeight.bold,
//     color: PdfColors.white,
//   );
//
//   final titleTextStyle = pw.TextStyle(
//     fontSize: 16,
//     fontWeight: pw.FontWeight.bold,
//     color: PdfColors.blueGrey800,
//   );
//
//   // Add a page
//   pdf.addPage(
//     pw.Page(
//       pageFormat: PdfPageFormat.a4,
//       margin: pw.EdgeInsets.all(20),
//       build: (pw.Context context) {
//         return pw.Column(
//           crossAxisAlignment: pw.CrossAxisAlignment.start,
//           children: [
//             // Header Section with Gradient
//             pw.Container(
//               width: double.infinity,
//               padding: pw.EdgeInsets.all(15),
//               decoration: pw.BoxDecoration(
//                 gradient: pw.LinearGradient(
//                   colors: [
//                     PdfColor.fromInt(0xFF3B5998), // Dark Blue
//                     PdfColor.fromInt(0xFF8B9DC3), // Light Blue
//                   ],
//                 ),
//               ),
//               child: pw.Text(
//                 'Occupant & Property Details',
//                 style: headerTextStyle,
//                 textAlign: pw.TextAlign.center,
//               ),
//             ),
//
//             pw.SizedBox(height: 20),
//
//             // Property Details Section with Background
//             pw.Container(
//               width: double.infinity,
//               padding: pw.EdgeInsets.all(10),
//               decoration: pw.BoxDecoration(
//                 color: PdfColors.blue100,
//                 borderRadius: pw.BorderRadius.circular(5),
//               ),
//               child: pw.Column(
//                 crossAxisAlignment: pw.CrossAxisAlignment.start,
//                 children: [
//                   pw.Text('Property Details', style: titleTextStyle),
//                   pw.SizedBox(height: 10),
//                   pw.Text(
//                     'Name: ${property.propertyName}\n'
//                         'Address: ${property.address}\n'
//                         'City: ${property.city}\n'
//                         'Location: ${property.location}\n'
//                         'Type: ${property.propertyType}\n'
//                         'Price: ${property.price} (${property.priceType})\n'
//                         'Available Units: ${property.availableFlatsRooms}, Occupied: ${property.occupiedFlatsRooms}\n'
//                         'Status: ${property.status}',
//                     style: baseTextStyle,
//                   ),
//                 ],
//               ),
//             ),
//
//             pw.SizedBox(height: 20),
//
//             // Occupant Details Section with Background
//             pw.Container(
//               width: double.infinity,
//               padding: pw.EdgeInsets.all(10),
//               decoration: pw.BoxDecoration(
//                 color: PdfColors.teal100,
//                 borderRadius: pw.BorderRadius.circular(5),
//               ),
//               child: pw.Column(
//                 crossAxisAlignment: pw.CrossAxisAlignment.start,
//                 children: [
//                   pw.Text('Occupant Details', style: titleTextStyle),
//                   pw.SizedBox(height: 10),
//                   pw.Text(
//                     'Name: ${occupant.name}\n'
//                         'Date of Birth: ${occupant.dob}\n'
//                         'Mobile Number: ${occupant.mobileNumber}\n'
//                         'Gender: ${occupant.gender}\n'
//                         'Room Number: ${occupant.roomNumber}\n'
//                         'Rent Paid: ${occupant.rentPaid}, Rent Due: ${occupant.rentDueDate}\n'
//                         'Occupation Status: ${occupant.occupationStatus}\n'
//                         'Relationship: ${occupant.relationship}',
//                     style: baseTextStyle,
//                   ),
//                 ],
//               ),
//             ),
//
//             pw.SizedBox(height: 20),
//
//             // Decorative Footer Section
//             pw.Divider(color: PdfColors.grey, thickness: 1),
//             pw.Center(
//               child: pw.Text(
//                 'Generated by Property Management System',
//                 style: pw.TextStyle(fontSize: 10, color: PdfColors.grey),
//               ),
//             ),
//           ],
//         );
//       },
//     ),
//   );
//
//   // Save the PDF
//   final directory = await getApplicationDocumentsDirectory();
//   final path = '${directory.path}/EnhancedOccupantAndPropertyDetails.pdf';
//   final file = File(path);
//   await file.writeAsBytes(await pdf.save());
//
//   // Share the PDF
//   await Printing.sharePdf(
//     bytes: await pdf.save(),
//     filename: 'EnhancedOccupantAndPropertyDetails.pdf',
//   );
// }
